AWSTemplateFormatVersion: "2010-09-09"
Resources:
  PubliclyAccessViolation:
    Type: "AWS::Redshift::Cluster"
    Properties:
      DBName: "mydb"
      MasterUsername: "master"
      MasterUserPassword:
        Ref: "MasterUserPassword"
      NodeType: "ds2.xlarge"
      ClusterType: "single-node"
      KmsKeyId: "test"
      Encrypted: true
      LoggingProperties:
        BucketName: "test"
      Tags:
        - Key: foo
          Value: bar
  NoKmsId:
    Type: "AWS::Redshift::Cluster"
    Properties:
      DBName: "mydb"
      MasterUsername: "master"
      MasterUserPassword:
        Ref: "MasterUserPassword"
      NodeType: "ds2.xlarge"
      ClusterType: "single-node"
      PubliclyAccessible: false
      Encrypted: true
      LoggingProperties:
        BucketName: "test"
      Tags:
        - Key: foo
          Value: bar
  NoEncryption:
    Type: "AWS::Redshift::Cluster"
    Properties:
      DBName: "mydb"
      MasterUsername: "master"
      MasterUserPassword:
        Ref: "MasterUserPassword"
      NodeType: "ds2.xlarge"
      ClusterType: "single-node"
      KmsKeyId: "test"
      PubliclyAccessible: false
      LoggingProperties:
        BucketName: "test"
      Tags:
        - Key: foo
          Value: bar
  NoLogging:
    Type: "AWS::Redshift::Cluster"
    Properties:
      DBName: "mydb"
      MasterUsername: "master"
      PubliclyAccessible: false
      MasterUserPassword:
        Ref: "MasterUserPassword"
      NodeType: "ds2.xlarge"
      ClusterType: "single-node"
      KmsKeyId: "test"
      Encrypted: true
      Tags:
        - Key: foo
          Value: bar
