AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  apiKeySourceType:
    Type: String
    Default: MyApiSrc
  apiName:
    Type: String
    Default: MyApi
  binaryMediaType1:
    Type: String
  binaryMediaType2:
    Type: String
  minimumCompressionSize:
    Type: String
Resources:
  MyRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      ApiKeySourceType: !Ref apiKeySourceType
      BinaryMediaTypes:
        - !Ref binaryMediaType1
        - !Ref binaryMediaType2
      MinimumCompressionSize: -1
      EndpointConfiguration:
        Types:
          - EDGE
      Name: !Ref apiName
      Policy: >-
        {
            "Version": "2012-10-17",
            "Statement": [
                            {
                                "Effect": "Allow",
                                "Principal": {
                                    "AWS": "*"
                                  },
                                "Action": "execute-api:Invoke",
                                "Resource": "${aws_api_gateway_rest_api.test.execution_arn}",
                                "Condition": {
                                    "IpAddress": {
                                        "aws:SourceIp": "123.123.123.123/32"
                                      }
                              }
                            }
                          ]
          }
