AWSTemplateFormatVersion: "2010-09-09"
Resources:
  scalerpolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: scalername
      PolicyType: TargetTrackingScaling
      ScalableDimension: dynamodb:table:ReadCapacityUnits
      ServiceNamespace: dynamodb