Resources:
  PublicBroker:
    Type: "AWS::AmazonMQ::Broker"
    Properties:
      BrokerName: MyBasicActiveBroker
      DeploymentMode: SINGLE_INSTANCE
      EngineType: ActiveMQ
      EngineVersion: "5.15.0"
      HostInstanceType: mq.t2.micro
      PubliclyAccessible: true
      Users:
        -
          ConsoleAccess: true
          Groups:
            - MyGroup
          Password:
            Ref: AmazonMqPassword
          Username:
            Ref: AmazonMqUsername
  NoLogsBroker:
    Type: "AWS::AmazonMQ::Broker"
    Properties:
      BrokerName: MyBasicActiveBroker
      DeploymentMode: SINGLE_INSTANCE
      EngineType: ActiveMQ
      EngineVersion: "5.15.0"
      HostInstanceType: mq.t2.micro
      Logs:
        Audit: false
        General: true
      Users:
        -
          ConsoleAccess: true
          Groups:
            - MyGroup
          Password:
            Ref: AmazonMqPassword
          Username:
            Ref: AmazonMqUsername
