Resources:
  MySecret:
      Type: 'AWS::SecretsManager::Secret'
      Properties:
          Description: This is a secret that I want to attach a resource-based policy to
  MySecretResourcePolicy:
      Type: 'AWS::SecretsManager::ResourcePolicy'
      Properties:
          SecretId: !Ref MySecret
          ResourcePolicy:
            Version: 2012-10-17
            Statement:
              - Resource: '*'
                Action: 'secretsmanager:*'
                Effect: Allow
                Principal:
                  AWS: '*'
