AWSTemplateFormatVersion: "2010-09-09"
Resources:
  fun:
    Type: AWS::Lambda::Function
    Properties:
      KmsKeyArn: somekeyarn
      FunctionName: funyun
      Code:
        S3Bucket: bucket1
        S3Key: key1
        S3ObjectVersion: version1
      Role: somerole
      Handler: somehandle
      MemorySize: 128
      ReservedConcurrentExecutions: -1
      Runtime: python
      Timeout: 30
      TracingConfig:
        Mode: Passive
      VpcConfig:
        SecurityGroupIds:
          - sg1
          - sg2
          - sg3
        SubnetIds:
          - subnet1
          - subnet2
      Environment:
        Variables:
          mona: lisa
          leo: vinci

